#!/bin/sh
# Render the Homebrew formula for a published release from its checksums.txt.
set -eu

tag=$1
checksums=$2
url="https://github.com/vertti/pg-tunnel/releases/download/$tag"

sha() {
  value=$(awk -v archive="pg-tunnel_$1.tar.xz" '$2 == archive { print $1 }' "$checksums")
  if [ -z "$value" ]; then
    echo "$checksums has no entry for pg-tunnel_$1.tar.xz" >&2
    exit 1
  fi
  echo "$value"
}

darwin_arm64=$(sha darwin_arm64)
darwin_amd64=$(sha darwin_amd64)
linux_arm64=$(sha linux_arm64)
linux_amd64=$(sha linux_amd64)

cat <<EOF
# Generated by pg-tunnel's Homebrew formula workflow. Do not edit.
class PgTunnel < Formula
  desc "Connect PostgreSQL clients to private AWS RDS databases through SSM"
  homepage "https://github.com/vertti/pg-tunnel"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$url/pg-tunnel_darwin_arm64.tar.xz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$url/pg-tunnel_darwin_amd64.tar.xz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$url/pg-tunnel_linux_arm64.tar.xz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$url/pg-tunnel_linux_amd64.tar.xz"
      sha256 "$linux_amd64"
    end
  end

  def install
    bin.install "pg-tunnel"
    doc.install "licenses", "third_party"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pg-tunnel --version 2>&1")
  end
end
EOF
